-- Table TASK
CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject TEXT NOT NULL,
    description TEXT,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO task (subject, description, completed)
VALUES
('Revisar pull requests', 'Verificar los cambios en el repositorio principal', false),
('Actualizar dependencias', 'Subir versiones de librerías desactualizadas', false),
('Escribir documentación', 'Agregar ejemplos y detalles al README', false),
('Planificar sprint', 'Definir tareas y tiempos para el siguiente sprint', true),
('Optimizar consultas SQL', 'Revisar índices y mejorar tiempos de respuesta', false),
('Testear módulo de login', 'Verificar flujos de autenticación y errores', true),
('Corregir bug en dashboard', 'Fix para el error al mostrar métricas', false),
('Preparar presentación', 'Diapositivas para reunión de stakeholders', true),
('Refactorizar código legacy', 'Mejorar mantenibilidad del módulo antiguo', false),
('Implementar endpoint de logout', 'Agregar endpoint seguro con token invalidation', true);
